### ISSUE TITLE
Running the app via WAMP server

### ISSUE THREAD

**Issue by callmiy** [Mike724/Frameworkless#3]
I am still learning the ropes in PHP. Now I'm trying to run this app via WAMP server. I know I need to use .htaccess and mod_rewrite. But I can't seem to figure out just what rule will enable me access both the home page and todos. I have settled on 

`
RewriteEngine on
RewriteRule .* public/index.php
`
but I keep getting `404 Not Found` error. Any help will be appreciated.

**Comment by mmeyer724** [comment]
The pattern being used here is called the front-controller pattern. You were on the right track, but I think your rewrite rule(s) are a bit off.

This should work for you: http://www.chrisabernethy.com/mod-rewrite-front-controller/

**Comment by callmiy** [comment]
Thanks @Mike724. I read the article and it enhanced my knowledge of apache and mod_rewrite. However it did not solve my problem. But I did something that worked.

I have the app files inside c:\wamp\www\frameworkless and so I had to access the app like so: localhost/frameworkless/todos (for example). So I edited c:\wamp\www\frameworkless\bootstrap\routes.php and changed the line
`['GET', '/todos', ['Frameworkless\Controllers\TodosController', 'get']]`
to
`['GET', '/frameworkless/todos', ['Frameworkless\Controllers\TodosController', 'get']]`
and it works. But I don't like prepending `/frameworkless` to all URIs. 

Can anybody help with how I can leave the code as
`['GET', '/todos', ['Frameworkless\Controllers\TodosController', 'get']]`

and get the .htaccess to work?

**Comment by mmeyer724** [comment]
I _highly_ recommend setting your DocumentRoot to the public/ directory (in this repo). Otherwise, I could navigate to:
http://webhost/frameworkless/.env
http://webhost/frameworkless/setup/
etc....

Right now your DocumentRoot is c:\wamp\www, which I assume is the default for WAMP. Change it to c:\wamp\www\frameworkless\public. 

edit: ignore what I said above about being able to navigate around and print sensitive files -- that is probably not possible due to how you're rewriting requests. Still, the best solution is to change the document root.

**Comment by callmiy** [comment]
Ok thanks. I will give that a shot.

**Comment by callmiy** [comment]
Ok I finally solved it. The reason I needed to do this is to mimic what is obtainable on my shared hosting.

#  .htaccess

```
Options -Indexes
IndexIgnore *

RewriteEngine on
RewriteRule .* public/index.php

RewriteCond %{THE_REQUEST} public/?|index\.php
RewriteRule public/?|index\.php - [F]
```

Then in bootstrap/app.php, I strip out 'frameworkless' from the request URL:

``` php
$url = str_replace( '/noframework', '', $request->getPathInfo() );  
$url = $url === '/' ? $url : rtrim( $url, '/' );
```

Thanks @Mike724
